// frontend/src/components/PropertyCard.vue
<script setup lang="ts">
import { computed } from 'vue'
import type { PropertyOut } from '@/types/api'

const props = defineProps<{ property: PropertyOut }>()

const formattedPrice = computed(() =>
  new Intl.NumberFormat('es-GT', {
    style: 'currency',
    currency: 'USD',
    maximumFractionDigits: 0,
  }).format(props.property.precio),
)

const formattedDate = computed(() =>
  new Intl.DateTimeFormat('es-GT', { day: 'numeric', month: 'long', year: 'numeric' }).format(
    new Date(props.property.fecha_publicacion + 'T00:00:00'),
  ),
)

const gradientByTipo: Record<string, string> = {
  casa: 'from-primary-100 to-primary-300',
  departamento: 'from-accent-100 to-accent-300',
  terreno: 'from-emerald-100 to-emerald-300',
  oficina: 'from-violet-100 to-violet-300',
  local: 'from-amber-100 to-amber-300',
}

const iconByTipo: Record<string, string> = {
  casa: 'M3 12 12 3l9 9M5 10v10h14V10',
  departamento: 'M3 21V7a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2v14M9 21V11M15 21V11',
  terreno: 'M3 12h18M3 18h18M3 6h18',
  oficina: 'M6 4h12v16H6zM10 8h4M10 12h4M10 16h4',
  local: 'M3 9 5 4h14l2 5M3 9v11h18V9M9 14h6',
}

const tipoLabelMap: Record<string, string> = {
  casa: 'Casa',
  departamento: 'Departamento',
  terreno: 'Terreno',
  oficina: 'Oficina',
  local: 'Local',
}

const tipoLabel = computed(
  () => tipoLabelMap[props.property.tipo] ?? props.property.tipo,
)
</script>

<template>
  <article class="card prop-card flex flex-col">
    <div
      class="aspect-[16/10] bg-gradient-to-br flex items-center justify-center relative"
      :class="gradientByTipo[property.tipo] ?? 'from-neutral-100 to-neutral-200'"
    >
      <span
        class="absolute top-3 left-3 inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-white/92 backdrop-blur-sm text-[11px] font-semibold text-neutral-800 shadow-sm"
      >
        <svg
          class="w-3 h-3 text-neutral-500"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
          stroke-linejoin="round"
          aria-hidden="true"
        >
          <path :d="iconByTipo[property.tipo]" />
        </svg>
        {{ tipoLabel }}
      </span>
      <svg
        class="w-16 h-16 text-white/90"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        stroke-width="1.5"
        stroke-linecap="round"
        stroke-linejoin="round"
        aria-hidden="true"
      >
        <path :d="iconByTipo[property.tipo]" />
      </svg>
    </div>
    <div class="p-5 flex flex-col gap-3 flex-1">
      <header class="flex items-start justify-between gap-3">
        <h3 class="text-h2 font-semibold leading-tight tracking-tight text-neutral-900">
          {{ property.titulo }}
        </h3>
        <p
          class="text-h2 text-primary-700 whitespace-nowrap font-semibold tabular-nums tracking-tight"
        >
          {{ formattedPrice }}
        </p>
      </header>
      <p v-if="property.descripcion" class="text-body text-neutral-600 line-clamp-2">
        {{ property.descripcion }}
      </p>
      <p class="text-caption text-neutral-500 flex items-center gap-1">
        <svg class="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
          <path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z" />
          <circle cx="12" cy="10" r="3" />
        </svg>
        {{ property.ubicacion }}
      </p>
      <div class="flex flex-wrap gap-2 mt-auto pt-2">
        <span v-if="property.habitaciones !== null" class="chip">
          {{ property.habitaciones }} hab.
        </span>
        <span v-if="property.banos !== null" class="chip">{{ property.banos }} baños</span>
        <span v-if="property.area_m2 !== null" class="chip">{{ property.area_m2 }} m²</span>
      </div>
      <footer class="pt-3 border-t border-neutral-100">
        <p class="text-caption text-neutral-400">Publicado el {{ formattedDate }}</p>
      </footer>
    </div>
  </article>
</template>

<style scoped>
.line-clamp-2 {
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
}
</style>

// design_handoff_uikit_redesign/reference/PropertyCard.jsx
// ui_kits/web/PropertyCard.jsx — single listing card
// Source: frontend/src/components/PropertyCard.vue
// Kit additions (flagged): tipo badge inside the gradient header, staggered fade-up entrance.

const fmtPrice = (n) =>
  new Intl.NumberFormat('es-GT', {
    style: 'currency',
    currency: 'USD',
    maximumFractionDigits: 0,
  }).format(n);

const fmtDate = (iso) =>
  new Intl.DateTimeFormat('es-GT', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  }).format(new Date(iso + 'T00:00:00'));

const TIPO_LABEL = {
  casa: 'Casa',
  departamento: 'Departamento',
  terreno: 'Terreno',
  oficina: 'Oficina',
  local: 'Local',
};

const PropertyCard = ({ property: p }) => {
  const TipoIcon = TIPO_ICONS[p.tipo] ?? HouseIcon;
  const gradient = TIPO_GRADIENTS[p.tipo] ?? 'linear-gradient(135deg, #f3f4f6, #e5e7eb)';

  return (
    <article className="card prop-card" style={{ display: 'flex', flexDirection: 'column' }}>
      <div
        style={{
          aspectRatio: 'var(--kit-card-image-ratio, 16 / 10)',
          background: gradient,
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          color: 'rgba(255,255,255,0.9)',
          position: 'relative',
        }}
      >
        {/* Tipo badge — kit addition */}
        <span style={{
          position: 'absolute',
          top: 12, left: 12,
          display: 'inline-flex',
          alignItems: 'center',
          gap: 6,
          padding: '4px 10px 4px 8px',
          borderRadius: 9999,
          background: 'rgba(255,255,255,0.92)',
          color: 'var(--neutral-800)',
          fontSize: 11,
          fontWeight: 600,
          letterSpacing: '0.01em',
          backdropFilter: 'blur(4px)',
          WebkitBackdropFilter: 'blur(4px)',
          boxShadow: '0 1px 2px rgba(15,58,110,0.08)',
        }}>
          <span style={{ color: 'var(--neutral-500)' }}>
            <TipoIcon size={12} strokeWidth={2} />
          </span>
          {TIPO_LABEL[p.tipo] ?? p.tipo}
        </span>
        <TipoIcon size={64} strokeWidth={1.5} />
      </div>
      <div style={{
        padding: 'var(--kit-card-pad, 20px)',
        display: 'flex',
        flexDirection: 'column',
        gap: 10,
        flex: 1,
      }}>
        <header style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 12 }}>
          <h3 style={{
            fontSize: 'var(--fs-h2)',
            lineHeight: 1.2,
            fontWeight: 600,
            color: 'var(--neutral-900)',
            margin: 0,
            letterSpacing: '-0.005em',
          }}>{p.titulo}</h3>
          <p style={{
            fontSize: 'var(--fs-h2)',
            color: 'var(--primary-700)',
            whiteSpace: 'nowrap',
            fontWeight: 600,
            margin: 0,
            fontVariantNumeric: 'tabular-nums',
            letterSpacing: '-0.01em',
          }}>{fmtPrice(p.precio)}</p>
        </header>
        {p.descripcion && (
          <p style={{
            fontSize: 'var(--fs-body)',
            color: 'var(--neutral-600)',
            display: '-webkit-box',
            WebkitLineClamp: 2,
            WebkitBoxOrient: 'vertical',
            overflow: 'hidden',
            margin: 0,
            lineHeight: 1.45,
          }}>{p.descripcion}</p>
        )}
        <p style={{
          fontSize: 'var(--fs-caption)',
          color: 'var(--neutral-500)',
          display: 'flex',
          alignItems: 'center',
          gap: 4,
          margin: 0,
        }}>
          <MapPinIcon size={14} />
          {p.ubicacion}
        </p>
        <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6, marginTop: 'auto', paddingTop: 6 }}>
          {p.habitaciones != null && <span className="chip">{p.habitaciones} hab.</span>}
          {p.banos != null && <span className="chip">{p.banos} baños</span>}
          {p.area_m2 != null && <span className="chip">{p.area_m2} m²</span>}
        </div>
        <footer style={{ paddingTop: 10, borderTop: '1px solid var(--neutral-100)' }}>
          <p style={{ fontSize: 'var(--fs-caption)', color: 'var(--neutral-400)', margin: 0 }}>
            Publicado el {fmtDate(p.fecha_publicacion)}
          </p>
        </footer>
      </div>
    </article>
  );
};

const PropertyGrid = ({ properties }) => (
  <div className="prop-grid">
    {properties.map((p) => (
      <div key={p.id} className="prop-card-wrap">
        <PropertyCard property={p} />
      </div>
    ))}
  </div>
);

window.PropertyCard = PropertyCard;
window.PropertyGrid = PropertyGrid;
window.fmtPrice = fmtPrice;
window.fmtDate = fmtDate;
